version: '3.7'
services:
  promtail:
    image: grafana/promtail:2.4.0
    restart: always
    volumes:
      - /var/log:/var/log
      - ./config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    logging:
      driver: loki
      options:
        loki-url: http://home.grafana:3100/loki/api/v1/push
        loki-batch-size: '400'
        loki-external-labels: 'job=docker,container_name={{.Name}},service=infra.promtail'
