version: '3.7'
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    user: '1000'
    ports:
      - 3001:3001
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - grafana:/var/lib/grafana
    networks:
      loki:
        ipv4_address: 172.100.0.10
    logging:
      driver: loki
      options:
        loki-url: http://home.grafana:3100/loki/api/v1/push
        loki-batch-size: '400'
        loki-external-labels: 'job=docker,container_name={{.Name}},service=home.grafana'
  loki:
    image: grafana/loki:2.4.0
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./data/loki:/etc/loki
      - loki:/loki
    networks:
      loki:
        ipv4_address: 172.100.0.11
    command: -config.file=/etc/loki/loki-config.yaml
      #  -server.http-listen-port=3100
    networks:
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://home.grafana:3100/loki/api/v1/push
        loki-batch-size: '400'
        loki-external-labels: 'job=docker,container_name={{.Name}},service=home.loki'

networks:
  loki:
    external: true

volumes:
  grafana:
  loki:
