---
- hosts: all
  tasks:

  - name: infra.node-exporter • copy files
    copy:
      src: ../services/infra.node-exporter
      dest: .
    notify: restart-node-exporter

  - name: infra.node-exporter • ufw • open port 9100 
    become: true
    ufw:
      rule: allow
      port: 9100
      from: '{{ hostvars["home.grafana"].ip4 }}'
      comment: home.grafana

  handlers:
  - name: infra.node-exporter • docker-compose stop
    docker_compose:
      project_src: infra.node-exporter
      stopped: true
      state: present
    listen: restart-node-exporter
  - name: infra.node-exporter • docker-compose up
    docker_compose:
      project_src: infra.node-exporter
      state: present
    listen: restart-node-exporter
