---
- hosts: all
  tasks:

# [DEPRECATION WARNING]: The connection's stdin object is deprecated. Call
# display.prompt_until(msg) instead. This feature will be removed in version
# 2.19. Deprecation warnings can be disabled by setting
# deprecation_warnings=False in ansible.cfg.
#  - name: Copy files/infra.promtail/
#    synchronize:
#      src: ../files/infra.promtail
#      dest: .
#      rsync_opts:
#        - '--exclude=*.jinja2'

  - name: infra.promtail • copy files/infra.promtail/
    copy:
      src: ../files/infra.promtail
      dest: .

  - name: infra.promtail • expand .jinja2 files
    template:
      src: ../files/infra.promtail/config/promtail-config.yaml.jinja2
      dest: infra.promtail/config/promtail-config.yaml

  - name: infra.promtail • spin up docker service
    docker_compose:
      project_src: infra.promtail
      state: present
