---
- hosts: all
  tasks:

  - name: infra.heartbeat • copy files
    copy:
      src: ../services/infra.heartbeat
      dest: .
    notify: restart-heartbeat

  handlers:
  - name: infra.heartbeat • docker-compose stop
    docker_compose:
      project_src: infra.heartbeat
      stopped: true
      state: present
    listen: restart-heartbeat
  - name: infra.heartbeat • docker-compose up
    docker_compose:
      project_src: infra.heartbeat
      state: present
    listen: restart-heartbeat
