---
- hosts: all
  tasks:

  - name: infra.promtail • copy files
    copy:
      src: ../services/infra.promtail
      dest: .
    notify: restart-promtail

  - name: infra.promtail • expand .jinja2 files
    template:
      src: ../services/infra.promtail/config/promtail-config.yaml.jinja2
      dest: infra.promtail/config/promtail-config.yaml
    notify: restart-promtail

  handlers:
  - name: infra.promtail • docker-compose stop
    docker_compose:
      project_src: infra.promtail
      stopped: true
      state: present
    listen: restart-promtail
  - name: infra.promtail • docker-compose up
    docker_compose:
      project_src: infra.promtail
      state: present
    listen: restart-promtail
