---
- hosts: all
  become: true
  tasks:
    - name: php8.1 • Install php 8.1
      apt:
        name:
          - php8.1
          - php8.1-mysql
          - php8.1-gd
          - php8.1-curl
          - php8.1-xml
          - php8.1-zip
          - php8.1-mbstring
          - php8.1-xdebug
          - php8.1-bcmath
          - php8.1-soap
          - php8.1-redis
          - php8.1-intl
        state: latest
        update_cache: true
